version: '3.7'

services:
  postgres-dev:
    image: postgres:latest
    container_name: pickngo-db
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
      POSTGRES_DB: db
    volumes:
      - ./db/:/var/lib/postgresql/pickngo-data
    ports:
      - 5432:5432
