on:
  push:
    branches: [ feature/gh-action ]
  pull_request:
    branches: [ feature/gh-action ]

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create Release With Asset
        id: Release-AIO
        uses: Hs1r1us/Release-AIO@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          asset_files: './test.txt'
