name: "pre-release"

on:
  push:
    branches:
      - "feature/gh-action"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            test.txt
            
      - name: Set up secret file
        env:
          DEBUG_PASSWORD: ${{ secrets.KEY }}
          DEBUG_SECRET_KEY: ${{ secrets.SERVER }}
          TEST: ${{ secrets.SERVER_USER }}
        run: |
          echo $DEBUG_PASSWORD >> secrets.txt
          echo $DEBUG_SECRET_KEY >> secrets.txt
          echo $TEST >> secrets.txt
          cat  secrets.txt

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
