
name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ feature/gh-action ]
  pull_request:
    branches: [ feature/gh-action ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Starting Deployment
        run: echo starting deployment

      - name: quarkus backend build jar file
        run: |
          cd backend/
          mvn package -Dquarkus.package.type=uber-jar
          ls target/*.jar

      - name: build angular dist folder
        run: |
          cd frontend/
          npm install -g @angular/cli
          npm install
          ng build
          tar -czvf dist.tar.gz dist 

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          release_name: Release ${{ steps.version.outputs.version }}
          artifacts: "backend/target/*.jar"
          body: |
            Changes in this Release
            -
          draft: false
          prerelease: false


