
name: deployy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ feature/gh-action ]
  pull_request:
    branches: [ feature/gh-action ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Starting Deployment
        run: echo starting deployment

      - name: TESTING
        run: |
          pwd
          ls

      - name: quarkus backend build jar file
        run: |
          cd backend/
          mvn package -Dquarkus.package.type=uber-jar
          mv ../../backend/target/pickngo-1.0.0-SNAPSHOT-runner.jar ../../../pickngo/

          
          


